config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  post '/address/new.user_id' => 'address#create'
  resources :address do

  end

  post	'/address/rants/:id'	=> 'rants#sent', as: 'sent'

  resources :users do
    resources :rants
  end

  post '/sign_up' => 'users#create'
  get '/sign_up' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :rants

  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, length: { is: 5 }

end

app/models/rant.rb
require 'httparty'

class Rant < ActiveRecord::Base
  belongs_to :user
  has_one :address

  validates :rant, presence: true
  validates :user_id, presence: true
  validates :address_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rants

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  has_secure_password

  def self.log_in(email, password)
    somebody = User.find_by(email: email.downcase)
    somebody && somebody.authenticate(password)
  end

  def current_user?(current_user)
    return false if current_user == nil
    current_user.id == self.id ? true : false
  end


end

app/controllers/address_controller.rb
require 'ContactWrapper'

class AddressController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :require_login, only: [:new, :create]

  def index
  end

  def show
  end

  def new
    if current_user
      @address = Address.find_by(user_id: session[:user_id])
      unless @address
        @address = Address.new
      end
    else
      @address = Address.new
    end
    if current_user
      @user = User.find(session[:user_id])
    else
      @user = User.new
    end
  end


  def create
      address_string = "#{params[:address]} #{params[:city]}, #{params[:state]}"


    @response = ContactWrapper.send_request(address_string)

    render "rants/new"
  end

  def update

  end
end

private
  def address_params
    params.permit(address: [:address, :address2, :city, :state, :zip, :user_id])

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
helper_method :current_user

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index


  end

  
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  skip_before_action :verify_authenticity_token
   skip_before_action :require_login, only: [:new, :update_cart, :destroy, :create, :show]


  def index
    if params[:user_id].to_i == current_user.id
      @user = User.find(current_user.id)
      @rant = Rant.new

    else
      redirect_to login_path
    end
  end

  def show
    if current_user
      @rant = Rant.find(params[:id])
    elsif current_user.nil?
      @rant = Rant.find(params[:rant_id])
    else
      @rant = Rant.find(params[:user_id])

    end

  end

  def new
    @rant = Rant.new
    @address = Address.new(address_params[:address])

  end

  def create
    @address = Address.new(address_params[:address])
    if @address.save
      @user_id = session[:user_id] if session[:user_id]
      @address_id = @address.id
      @rant = Rant.new( address_id: @address_id, user_id: @user_id)
      if @rant.save
        render sent_path
      end
    end
  end

  



    def address_params
      params.permit(address: [:address, :address2, :city, :state, :zip, :user_id])

    end
end


#old code that works if this breaks:
  # def new
  #   @rant = Rant.new  #(rant_create_params))
  #   @user = User.find_by(id: session[:user_id])
  #
  # end
  #
  # def address
  #   #save address to rant...add in model and ?
  #   if current_user
  #     @address = Address.find_by(user_id: session[:user_id])
  #     unless @address
  #       @address = Address.new
  #     end
  #   else
  #     @address = Address.new
  #   end
  #   if current_user
  #     @user = User.find(session[:user_id])
  #   else
  #     @user = User.new
  #   end
  # end
  #
  # end
  #
  # def create
  #   if session[:user_id]
  #     @user = User.find_by(id: session[:user_id])
  #     #save rant to user
  #     @rant = @user.rants.new(rant_create_params[:rant])
  #
  #     render :new
  #   else
  #     redirect_to new_user_path
  #   end
  # end
  #
  # def show
  #
  # end
  #
  # def sent
  #
  # end
  #
  #
  #
  #
  # private
  # def rant_create_params
  #   params.permit(rant: [:id, :uid, :rant, :created_at, :updated_at])
  # end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]

  # #create signs in a user by finding the id in User model and assigning session[:user_id]
  # use keep_cart_items

  # #destroy signs out a user by destroying the sessions[:user_id]

  def new
  end

  def create
    @user = User.log_in(params[:session][:email], params[:session][:password])

    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  def session_create_params
    params.permit(session: [:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_create_params[:user])
    if @user.save
      flash[:success] = "Success!!!"

      session[:user_id] = @user.id


      redirect_to root_path

    else
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  render :show
  end

  def edit
    @user = User.find(params[:id])
    render :new
  end

  private

  def user_create_params
    params.permit(user: [:name, :username, :email, :password, :password_confirmation])
  end
end









# class UsersController < ApplicationController
#   #skip_before_action :require_login, only: [:new, :create, :show]
#   def new
#     @user = User.new
#   end
#
#   def create
#     @user = User.new(user_create_params[:user])
#     @user.save
#     if @user.save
#       session[:user_id] = @user.id
#       redirect_to user_path(@user)
#     else
#       @user = User.new(user_create_params[:user])
#       render :new
#     end
#   end
#
#   def show
#     @user = User.find(params[:id])
#
#   end
#
#   def edit
#     @user = User.find(params[:id])
#     render :new
#   end
#
#   def update
#     user = User.find(params[:id])
#     user.update(user_create_params[:user])
#     if user_create_params[:user][:merchant] == false
#       user.products.update_all(retired: "true")
#     else
#       user.products.update_all(retired: "false")
#     end
#     redirect_to user_path(user)
#   end
#
#   private
#
#   def user_create_params
#     params.permit(user: [:utf8, :authenticity_token, :commit, :name, :username, :email, :password, :password_confirmation,:photo_url, :biography, :merchant])
#   end
# end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/address/new.html.erb
<div class= "addysearch">
  <h3>Find My Local Reps:</h3>
  <br>
  <div class="address">
  	<div class="row">
  		 <form class="form-horizontal" accept-charset="UTF-8" url: '/address/new.user_id' method="post" >
         <!-- <input name="utf8" type="hidden" value="&#x2713;" /> -->
         <!-- <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" /> -->

              <fieldset>
                  <!-- Address form -->


                  <!-- address-line1 input-->
                  <div class="control-group">
                      <label class="control-label">Address Line 1</label>
                      <div class="controls">
                          <input id="address" name="address" type="text" placeholder="address line 1"
                          class="input-xlarge">
                          <p class="help-block">Street address, P.O. box, company name, c/o</p>
                      </div>
                  </div>
                  <!-- address-line2 input-->
                  <div class="control-group">
                      <label class="control-label">Address Line 2</label>
                      <div class="controls">
                          <input id="address-line2" name="address-line2" type="text" placeholder="address line 2"
                          class="input-xlarge">
                          <p class="help-block">Apartment, suite , unit, building, floor, etc.</p>
                      </div>
                  </div>
                  <!-- city input-->
                  <div class="control-group">
                      <label class="control-label">City / Town</label>
                      <div class="controls">
                          <input id="city" name="city" type="text" placeholder="city" class="input-xlarge">
                          <p class="help-block"></p>
                      </div>
                  </div>
                  <!-- region input-->
                  <div class="control-group">
                      <label class="control-label">State / Province / Region</label>
                      <div class="controls">
                          <input id="region" name="region" type="text" placeholder="state / province / region"
                          class="input-xlarge">
                          <p class="help-block"></p>
                      </div>
                  </div>
                  <!-- postal-code input-->
                  <div class="control-group">
                      <label class="control-label">Zip / Postal Code</label>
                      <div class="controls">
                          <input id="postal-code" name="postal-code" type="text" placeholder="zip or postal code"
                          class="input-xlarge">
                          <p class="help-block"></p>
                      </div>
                  </div>

                  <div class="control-group">
                      <div class="submit">
                        <button type="submit" class="btn btn-primary">Save</button>
                      </div>

                  </div>

              </fieldset>
          </form>
  	</div>
  </div>
</div>

app/views/home/index.html.erb
<div class ="image">
  <%=image_tag "polirant.png" %>
</div>

<div class="description" >

  <h1> You have a Voice...make it heard! </h1>



    <p>
      In many online community groups and in personal discussion, many people share their concerns, thoughts and
      suggestions involving various aspects of their local community/neighborhood. However, often these ideas are
      expressed and go no further than that; researching who to express these concerns to in order to make an impact  can
      seem overwhelming or fruitless …enter PoliRant.</p>
    <br>
    <p>
      PoliRant gives community members a resource to connect them with
      those in elected office, and help them become involved in initiating change by addressing community concerns.
      It's a personal letter from you to your representatives. Communicate your viewpoint, your reality, your
      concerns, and have them heard directly by those elected to represent us.</p>
</div>

<div class= "photos">

  <div class= "popular_rants">
    <%=image_tag "popular_rants.png" %>
    <h3>Popular Rants</h3>
  </div>

  <div class= "success_stories">
    <%=image_tag "success_stories.png" %>
    <h3>Success Stories</h3>
  </div>

  <div class= "other_causes">
    <%=image_tag "other_causes.png" %>
    <h3>Other Causes</h3>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polirant</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="build.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <div class ="logo">
    <%=image_tag "politext.png" %>


  <div class="container">
  	<div class="row">
  		<h4>Find My Reps!</h4>
        <div class="search">
  <input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter your Address (Street, City, State, Zip)" />
   <button type="submit" class="btn btn-primary btn-sm">Search</button>
  </div>
  	</div>
  </div>

  <div class= "poli_values">
    <h3> Truth....Accountability....Change! </h3>
  </div>


  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <div class="navbar-header">
      <a class="navbar-brand" href="#">PoliRant!</a>
    </div>

        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "HOME", root_path %></li>
          <li><%= link_to "New Rant", new_address_path(:user_id) %></li>
        </ul>



        <% if session[:user_id] %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to user_path(:id) do %><span class="glyphicon glyphicon-user"></span> User Profile<% end %></li>
          <li><%= link_to logout_path, method: "delete" do %><span class="glyphicon glyphicon-log-out"></span> Log Out<% end %></li>
        </ul>
            <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to new_user_path do %><span class="glyphicon glyphicon-user"></span> Sign Up<% end %></li>
              <li><%= link_to login_path do %><span class="glyphicon glyphicon-log-in"></span> Log In<% end %></li>
            </ul>
        <% end %>
    </div>
  </nav>

</header>
<body>

<%= yield %>

</body>

<footer class="footer-distributed">

  <div class="footer-left">

    <%=image_tag "lillogo.png" %>

    <p class="footer-links">
      <a href="#">Public Rants</a>
      ·
      <a href="#">Help</a>
      ·
      <a href="#">About</a>
      ·
      <a href="#">Faq</a>
      ·
      <a href="#">Contact</a>
    </p>

    <br>

    <p class="footer-company-name">PoliRant &copy; 2015</p>
  </div>

  <div class="footer-center">

    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>21 rEvolution Street</span> Seattle, WA</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>+1 555 123456</p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:support@company.com">support@polirant.com</a></p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>About the company</span>
      Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
    </p>


  </div>

</footer>
</html>

app/views/rants/address.html.erb
<div class= "addysearch">
  <h3>Find My Local Reps:</h3>
  <br>
  <div class="address">
  	<div class="row">
  		 <form class="form-horizontal" accept-charset="UTF-8" url: '/users/:user_id/rants' method="post" >
         <!-- <input name="utf8" type="hidden" value="&#x2713;" /> -->
         <!-- <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" /> -->

              <fieldset>
                  <!-- Address form -->


                  <!-- address-line1 input-->
                  <div class="control-group">
                      <label class="control-label">Address Line 1</label>
                      <div class="controls">
                          <input id="address-line1" name="address-line1" type="text" placeholder="address line 1"
                          class="input-xlarge">
                          <p class="help-block">Street address, P.O. box, company name, c/o</p>
                      </div>
                  </div>
                  <!-- address-line2 input-->
                  <div class="control-group">
                      <label class="control-label">Address Line 2</label>
                      <div class="controls">
                          <input id="address-line2" name="address-line2" type="text" placeholder="address line 2"
                          class="input-xlarge">
                          <p class="help-block">Apartment, suite , unit, building, floor, etc.</p>
                      </div>
                  </div>
                  <!-- city input-->
                  <div class="control-group">
                      <label class="control-label">City / Town</label>
                      <div class="controls">
                          <input id="city" name="city" type="text" placeholder="city" class="input-xlarge">
                          <p class="help-block"></p>
                      </div>
                  </div>
                  <!-- region input-->
                  <div class="control-group">
                      <label class="control-label">State / Province / Region</label>
                      <div class="controls">
                          <input id="region" name="region" type="text" placeholder="state / province / region"
                          class="input-xlarge">
                          <p class="help-block"></p>
                      </div>
                  </div>
                  <!-- postal-code input-->
                  <div class="control-group">
                      <label class="control-label">Zip / Postal Code</label>
                      <div class="controls">
                          <input id="postal-code" name="postal-code" type="text" placeholder="zip or postal code"
                          class="input-xlarge">
                          <p class="help-block"></p>
                      </div>
                  </div>

                  <div class="control-group">
                      <div class="submit">
                        <button type="submit" class="btn btn-primary">Save</button>
                      </div>

                  </div>

              </fieldset>
          </form>
  	</div>
  </div>
</div>

app/views/rants/new.html.erb
<!DOCTYPE html>
<html lang="en">


  <div class="rant">



    <div class="table">
      <h2>Rep Contacts:</h2>

      <!-- eventually this will be a loop that iterates through the data recieved form the wrapper -->




      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>
            <tbody>
              <% @response.officials.each do |official| %>
                <tr>
                  <% if official["emails"] %>
                    <td><%= official["name"] %></td>
                    <td><%= official["emails"].join(', ') %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
        </table>
    </div>

    <%= form_tag "rants/:id", :id => "my_form" do %>
    <h3><label for="comment">Listen up...</label></h3>
    <br>
    <%= text_area_tag "comment" %>
    <%= submit_tag "Send it out!" %>
    <% end %>

    <p> Take the space you need; drag the botton-right corner of the rant area to increase its size.</p>
  </div>
</html>

app/views/rants/sent.html.erb
<div class= "sent">
  <h3>      Thank you! Your rant has been sent! </h3>
</div>

app/views/rants/show.html.erb
<p> your rant has been sent! </p>

app/views/users/new.html.erb
<div class= "signup">

  <% if @user.errors.any? %>
  <div class="errors"
  <h2> Sorry, </h2>
  <ul>
    <% @user.errors.each do |attribute, message| %>
      <li>
        <strong><%= attribute %></strong>: <%= message %>
      </li>
      <% end %>
    </ul>
    <% end %>


    <h1>Signup!</h1>

    <div class="form">
      <%= form_for @user, :html => { :class => "form-horizontal", :class => "form" } do |f| %>

      <div class="control-group">
        <%= f.label :'username:', :class=>"control-label" %>
        <%= f.text_field :username, :class=>"form-control" %>
      </div>

      <div class="control-group">
        <%= f.label :'name:', :class=>"control-label" %>
        <%= f.text_field :name, :class=>"form-control" %>
      </div>

      <div class="control-group">
        <%= f.label :'email:', :class=>"control-label" %>
        <%= f.text_field :email, :class=>"form-control" %>
      </div>

      <div class="control-group">
        <%= f.label :'password:', :class=>"control-label" %>
        <%= f.password_field :password, :class=>"form-control" %>
      </div>

      <div class="control-group">
        <%= f.label :'password confirmation:', :class=>"control-label" %>
        <%= f.password_field :password_confirmation, :class=>"form-control" %>
      </div>
      <br>
      <div class="agreement">
        <h3> Terms of Use </h3>
        <br>
        <p> Freedom of speech is awesome! So is being kind. Here at PoliRant we believe that everyone deserves kindness and clarity. A compelling speech can be better made <strong>without</strong> insults, hurtful words, or cussing.</p>
        <br>
        <p> By signing up to use PoliRant, you agree to exercise this philosophy in any and all rants (ie. no cussing or other disrepectful language, and especially no threats or the like). <br>
          Failure to be a kind person while being proactive and engaging a representative will lead to your account being deleted....boom. Sorry, not sorry.</p>
          <br>
          <p>It's easy to cuss and scream and yell... it's harder to make a compelling argument that engages someone and diplomatically ignites change! Challenge your language and communication to make a difference in the world by sharing your perspective and passion effectively.</p>
          <br>
          <p> My grandma used to say, "You can catch more flies with sugar than vinegar." Dont go spraying vinegar. Let's use awareness, clarity and kindness to make the change we wish to see in the world! Yes we can!</p>
          <br>
          <p> By clicking the button below, you are agreeing to these terms. </p>
        </div>
        <br>

        <div class="form-actions">
            <%= f.submit class:'btn btn-success' %>
          </div>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="userinfo">

  <h2><%= @user.username.capitalize %></h2>
    <br>
	<p><%= @user.name %></p>
  <p><%= @user.email %></p>

	<div class="profile-usermenu">
		<ul class="nav">


      <% if @user.current_user?(current_user) %>
        <li class = "link">
          <%= link_to edit_user_path(@user) do%>
          <i class="glyphicon glyphicon-user"></i>
          Update Account
          <% end %>
        </li>
      <% end %>
		</ul>

    <% if @user.current_user?(current_user) %>
      <li class = "link">
        <%= link_to user_rants_path(@user) do%>
        Your Rants
        <% end %>
      </li>
    <% end %>


	</div>

</div>